DELETE  http://localhost:2000/api/persons/revoke HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "meta": {
        "userId": "5f3cd9d53fe10c4318ccabd8",
        "placeId": "5f3cd9e83fe10c4318ccabd9",
        "personId": "5f3e8c0a99833d262c710272",
        "departmentId": "5f3e57247a012e32dcbd4c86"
    }
}

###
DELETE http://localhost:2000/api/departments/revoke HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "meta": {
        "userId": "5f3cd9d53fe10c4318ccabd8",
        "placeId": "5f3cd9e83fe10c4318ccabd9",
        "personId": "5f3e8c0a99833d262c710272",
        "departmentId": "5f3e700aba77b535b00ff8e1"
    }
}