POST http://localhost:2000/api/persons HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "personId": "1234",
  "firstName": "Oğuz",
  "lastName": "Kurttutan",
  "phone1": "523-232-22-22",
  "address1": "Izmir Buca Turkiye",
  "email": "mert@mail.com"

}

###
GET http://localhost:2000/api/persons HTTP/1.1
Accept: application/json

###
GET http://localhost:2000/api/persons/5f3004a00b01650378b3fdd3 HTTP/1.1
Accept: application/json

###
PUT http://localhost:2000/api/persons/5f3004a00b01650378b3fdd3 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "phone1": "412-222-222"
}

###
DELETE  http://localhost:2000/api/persons/5f3004a00b01650378b3fdd3 HTTP/1.1
Accept: application/json