POST http://localhost:2000/api/persons/create/5f30403bee83451364614843 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjMwNDAzYmVlODM0NTEzNjQ2MTQ4NDMiLCJpYXQiOjE1OTY5OTk3NTF9.h2Oxi2sdjJxYUbHxetTJwKtZzHXqxHu7RraElKxRyMU

{
  "personId": "1234",
  "firstName": "Oğuz",
  "lastName": "Kurttutan",
  "phone1": "523-232-22-22",
  "address1": "Izmir Buca Turkiye",
  "email": "mert@mail.com"

}

###
GET http://localhost:2000/api/persons/list/5f30403bee83451364614843 HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjMwNDAzYmVlODM0NTEzNjQ2MTQ4NDMiLCJpYXQiOjE1OTY5OTk3NTF9.h2Oxi2sdjJxYUbHxetTJwKtZzHXqxHu7RraElKxRyMU

###
GET http://localhost:2000/api/persons/5f30505e4d7f1410f02ba66b HTTP/1.1
Accept: application/json

###
PUT http://localhost:2000/api/persons/5f3004a00b01650378b3fdd3 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "phone1": "412-222-222"
}

###
POST http://localhost:2000/api/persons/5f30163ad8be7510a8545af1 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "doorId": "12345678"
}

###
DELETE  http://localhost:2000/api/persons/5f30403bee83451364614843 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjMwNDAzYmVlODM0NTEzNjQ2MTQ4NDMiLCJpYXQiOjE1OTY5OTk3NTF9.h2Oxi2sdjJxYUbHxetTJwKtZzHXqxHu7RraElKxRyMU

{
  "id": "5f30488b4582ca13f8aa4da6"
}