POST http://localhost:2000/api/rules HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "data": {
        "doors": [
            "5f3eb94382bda00a38d6e4c0", 
            "5f3eb95882bda00a38d6e4c2"
        ],
        "dateType": 3,
        "oneDay": "2011-10-05T14:48:00.000Z",
        "clockInterval": {
            "to": ["23", "00"],
            "from": ["10", "15"]
        }
    },
    "meta": {
        "userId": "5f3eb8d282bda00a38d6e4b9",
        "placeId": "5f3eb8e382bda00a38d6e4ba",
        "departmentId": "5f3eb9ce82bda00a38d6e4c9"
    }

}

###
POST http://localhost:2000/api/rules HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "data": {
        "doors": [
            "5f3eb94382bda00a38d6e4c0", 
            "5f3eb95882bda00a38d6e4c2"
        ],
        "dateType": 1,
        "dateInterval":{
            "to": "2011-10-05T14:48:00.000Z",
            "from": "2011-10-01T14:48:00.000Z"
        },
        "clockInterval": {
            "to": ["23", "00"],
            "from": ["10", "15"]
        }
    },
    "meta": {
        "userId": "5f3eb8d282bda00a38d6e4b9",
        "placeId": "5f3eb8e382bda00a38d6e4ba",
        "departmentId": "5f3eb9ce82bda00a38d6e4c9"
    }

}

###
POST http://localhost:2000/api/rules HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "data": {
        "doors": [
            "5f3eb94382bda00a38d6e4c0", 
            "5f3eb95882bda00a38d6e4c2"
        ],
        "dateType": 2,
        "daysInWeek":[1,2,5],
        "clockInterval": {
            "to": ["23", "00"],
            "from": ["10", "15"]
        }
    },
    "meta": {
        "userId": "5f3eb8d282bda00a38d6e4b9",
        "placeId": "5f3eb8e382bda00a38d6e4ba",
        "departmentId": "5f3eb9ce82bda00a38d6e4c9"
    }

}