GET http://localhost:2000/api/users HTTP/1.1
Accept: application/json

###
POST http://localhost:2000/api/users/create/5f305c036392d01f9c650a76 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjMwNWMwMzYzOTJkMDFmOWM2NTBhNzYiLCJpYXQiOjE1OTcwMDQ4ODR9.qkER35bCR-9Q2gsUGfavZTB12hRM-n7jtWGhJ6ZF9SI

{
    "username": "oguz1",
    "password": "123456",
    "email": "oguz1@mail.com",
    "appID": "maksisoft2020"
}

###
GET http://localhost:2000/api/users/5f30505e4d7f1410f02ba66b HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjJlZDQzZTVjZGVkMzFhMDA0OGI2YWMiLCJpYXQiOjE1OTY5MDQ4MDV9.VR2uHtb3HGWM8OL_4mWABQ66lRroqMpBDgmyLJFdxG8

###
PUT http://localhost:2000/api/users/5f2ee7ae918bd1152c61e8b5 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjJlZTdhZTkxOGJkMTE1MmM2MWU4YjUiLCJpYXQiOjE1OTY5MDk2OTR9.4X4VpeuKB4Q7th2C_ugJS84oSvudDgzsmsg4ayX2XqA

{
    "email": "oguz123@gmail.com"
}
###
DELETE  http://localhost:2000/api/users/5f2ee7ae918bd1152c61e8b5 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjJlZTdhZTkxOGJkMTE1MmM2MWU4YjUiLCJpYXQiOjE1OTY5MDk2OTR9.4X4VpeuKB4Q7th2C_ugJS84oSvudDgzsmsg4ayX2XqA

{
    "email": "oguz123@gmail.com"
}

###
POST http://localhost:2000/auth/signin HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123"
}

###

GET  http://localhost:2000/auth/signout HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "oguz01"
}

###
POST http://localhost:2000/api/master/create HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123",
    "email": "admin@mail.com",
    "isMaster": true
}