###
POST http://localhost:2000/api/users HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjMxYzQyNWM2ZGQyYjA4ZDg1YWJkZTEiLCJpYXQiOjE1OTcyNjY0NTR9.ZpX8DLSn_sGjRri32-OtOjhOGyWPi-1OJ_0-JA0dF98
x-app-id: maksisoft2020

{
    "username": "kemal",
    "password": "kemal123",
    "email": "kemal@mail.com"
}

###

POST http://localhost:2000/auth/signin HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "kemal",
    "password": "kemal123"
}