POST http://localhost:2000/api/master/create HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123",
    "email": "admin@mail.com",
    "isMaster": true
}

###

POST http://localhost:2000/auth/signin HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123"
}

###
GET http://localhost:2000/auth/signout/5f324ec2c2bae01c500fe6fe HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjMyNGVjMmMyYmFlMDFjNTAwZmU2ZmUiLCJpYXQiOjE1OTcxMzI1MDJ9.id2gs9toYf1nIuPkDRdHxHPcKWhbxTaKflYIQiAobac

###
GET http://localhost:2000/api/users HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjMxYzQyNWM2ZGQyYjA4ZDg1YWJkZTEiLCJpYXQiOjE1OTcyNjY0NTR9.ZpX8DLSn_sGjRri32-OtOjhOGyWPi-1OJ_0-JA0dF98
x-app-id: maksisoft2020

###
POST http://localhost:2000/api/users HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjMyYTA2YWM1YmNiNTMzZWM5NTlhMGQiLCJpYXQiOjE1OTcxNTMzOTR9.wV7C7kqOdioisWPVWRM3ktyFiYyhoXEc_nrIjGJsFG4
x-app-id: maksisoft2020

{
    "username": "oguz",
    "password": "oguz123",
    "email": "oguz@mail.com"
}

###
GET http://localhost:2000/api/users/5f324f3ac2bae01c500fe6ff HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjMyNGVjMmMyYmFlMDFjNTAwZmU2ZmUiLCJpYXQiOjE1OTcxMzI1NjV9.b0XeYbzAnpjNeBMG7rn_U5K3m7icMjbjxsTC7_gKioA
x-app-id: maksisoft2020

###

POST http://localhost:2000/auth/signin HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "oguz",
    "password": "oguz123"
}

###
GET http://localhost:2000/api/users/5f324f3ac2bae01c500fe6ff HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjMyNGYzYWMyYmFlMDFjNTAwZmU2ZmYiLCJpYXQiOjE1OTcxMzI2NDd9.On29flQeR5xJ87JKXGhk6XASKN2wLe13hsg2RY0tYVk

###
PUT http://localhost:2000/api/users/5f324f3ac2bae01c500fe6ff HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjMyNGYzYWMyYmFlMDFjNTAwZmU2ZmYiLCJpYXQiOjE1OTcxMzI2NDd9.On29flQeR5xJ87JKXGhk6XASKN2wLe13hsg2RY0tYVk

{
    "email": "oguz123@gmail.com"
}

###
PUT http://localhost:2000/api/users/5f324f3ac2bae01c500fe6ff HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjMyNGVjMmMyYmFlMDFjNTAwZmU2ZmUiLCJpYXQiOjE1OTcxMzI1NjV9.b0XeYbzAnpjNeBMG7rn_U5K3m7icMjbjxsTC7_gKioA
x-app-id: maksisoft2020

{
    "email": "oguz541@gmail.com"
}

###
DELETE  http://localhost:2000/api/users/5f324f3ac2bae01c500fe6ff HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjMyNGYzYWMyYmFlMDFjNTAwZmU2ZmYiLCJpYXQiOjE1OTcxMzI2NDd9.On29flQeR5xJ87JKXGhk6XASKN2wLe13hsg2RY0tYVk

###
DELETE http://localhost:2000/api/users/5f3251edb70fe40c5871a2d5 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjMyNGVjMmMyYmFlMDFjNTAwZmU2ZmUiLCJpYXQiOjE1OTcxMzI1NjV9.b0XeYbzAnpjNeBMG7rn_U5K3m7icMjbjxsTC7_gKioA
x-app-id: maksisoft2020